version: '3.9'

services:
  fastapi:
    container_name: "fast_filer_container"
    build:
      context: ..
      dockerfile: fast_filer/fastapi.Dockerfile
    env_file:
      - .env
    restart: always
    networks:
      - localhost-network
    volumes:
      - ${LOCAL_UPLOAD_PATH}:${FILE_STORAGE_PATH}

  nginx:
    build:
      context: ..
      dockerfile: fast_filer/nginx.Dockerfile
    container_name: nginx_fast_filer_container
    ports:
      # Port FastAPI
      - "9988:80"
    restart: always
    networks:
      - localhost-network

volumes:
  nginx_data:

networks:
  localhost-network:
    driver: bridge